/*
 * tiles.h - sprite atlas (generated by tools/gen_tiles.py from the graphics of Blips and own artwork).
 * One column of 16x16 tiles in the framebuffer pixel order; 0xF81F = transparent.
 * SPDX-License-Identifier: MIT
 */
#pragma once

#include <stdint.h>

enum TileId {
    T_FLOOR = 0, T_WALL, T_WALLB, T_COIN, T_BOMB, T_BOX, T_BOX1, T_BOX2, T_BOXBOMB, T_BOXWALL, T_ERASE,
    T_EXPL = 11,           // 8 frames
    T_PLAYER = 19,         // 16 frames: left 0-3, right 4-7, up 8-11, down 12-15
    T_PLAYER2 = 35,        // same for player 2
    T_COUNT = 51
};

constexpr int TS = 16;                      // tile size in pixels
constexpr uint16_t TILE_KEY = 0xF81F;

extern const uint16_t TILES_16[T_COUNT * TS * TS];
