// GENERATED by tools/gen_i18n.py - edit the table there, not this file.
// UTF-8, lowercase accents only (the 8x8 font has no uppercase accented glyph).
#include "i18n.h"

namespace i18n {

static int s_lang = FR;

static const char* const T[LANG_COUNT][S_COUNT] = {
  {  // FR
    "Jouer",  // S_PLAY
    "Comment jouer",  // S_HOWTO
    "Options",  // S_OPTIONS
    "Crédits",  // S_CREDITS
    "Quitter",  // S_QUIT
    "Choisis un pack",  // S_CHOOSE_PACK
    "%d niveaux",  // S_LEVELS_FMT
    "Niveau %d",  // S_LEVEL_FMT
    "par %s",  // S_BY_FMT
    "Pièces",  // S_COINS
    "Niveau terminé !",  // S_SOLVED
    "A : niveau suivant",  // S_SOLVED_NEXT
    "Pack terminé, bravo !",  // S_PACK_DONE
    "Dommage, c'est raté !",  // S_DIED
    "A:réessayer  B:niveaux",  // S_DIED_HELP
    "Retour au choix des niveaux ?",  // S_CONFIRM_LEVELS
    "Recommencer le niveau ?",  // S_CONFIRM_RELOAD
    "A:oui  B:non",  // S_CONFIRM_HELP
    "Pause",  // S_PAUSE
    "Reprendre",  // S_RESUME
    "Recommencer",  // S_RESTART
    "Choix du niveau",  // S_LEVEL_SELECT
    "Ecran titre",  // S_TO_TITLE
    "Langue",  // S_OPT_LANGUAGE
    "Musique",  // S_OPT_MUSIC
    "Bruitages",  // S_OPT_SFX
    "Tous les niveaux",  // S_OPT_UNLOCK
    "oui",  // S_ON
    "non",  // S_OFF
    "Retour",  // S_BACK
    "Aucun pack de niveaux",  // S_NO_PACKS
    "Niveau illisible",  // S_LOAD_ERROR
    "Capture enregistrée",  // S_SHOT_SAVED
    "Capture impossible",  // S_SHOT_FAILED
    "A:valider B:retour",  // S_HELP_MENU
    "A:jouer B:retour L/R:+-5",  // S_HELP_LEVELS
    "Ramasse toutes les pièces.",  // S_HOW1
    "Pousse les caisses (jamais deux).",  // S_HOW2
    "La dynamite tue : pousse une",  // S_HOW3
    "caisse dessus pour la faire sauter.",  // S_HOW4
    "Caisse-bombe : détruit murs fissurés",  // S_HOW5
    "et caisses. Deux caisses-mur = un mur.",  // S_HOW6
    "A : changer de joueur (2 joueurs)",  // S_HOW7
    "D + croix : regarder autour",  // S_HOW8
    "B : niveaux   C : recommencer",  // S_HOW9
    "Jeu d'origine",  // S_CR_TITLE_GAME
    "Graphismes",  // S_CR_TITLE_ART
    "Musique et sons",  // S_CR_TITLE_SOUND
    "Niveaux",  // S_CR_TITLE_LEVELS
    "Portage AKA",  // S_CR_TITLE_PORT
    "%d/%d",  // S_PAGE_FMT
    "Editeur de niveaux",  // S_EDITOR
    "Mes packs (éditeur)",  // S_ED_PACKS_TITLE
    "Nouveau pack",  // S_ED_NEW_PACK
    "Nouveau niveau",  // S_ED_NEW_LEVEL
    "Nom du nouveau pack",  // S_ED_NAME_TITLE
    "haut/bas:lettre gauche/droite:place",  // S_ED_NAME_HELP
    "D:effacer  A:ok  B:annuler",  // S_ED_NAME_HELP2
    "Ce nom existe déjà",  // S_ED_EXISTS
    "Tester le niveau",  // S_ED_TEST
    "Enregistrer et quitter",  // S_ED_SAVE
    "Quitter sans enregistrer",  // S_ED_DISCARD
    "Tout effacer",  // S_ED_CLEAR
    "Centrer le niveau",  // S_ED_CENTER
    "Niveau enregistré",  // S_ED_SAVED
    "Ecriture impossible",  // S_ED_SAVE_FAILED
    "D encore : supprimer",  // S_ED_DELETE_CONFIRM
    "Test réussi !",  // S_ED_TEST_OK
    "A:pose C:efface L/R:pièce D:test B:menu",  // S_ED_HELP
    "A:éditer D x2:supprimer B:retour",  // S_ED_LIST_HELP
    "Il manque un joueur",  // S_ED_NO_PLAYER
    "Il manque des pièces",  // S_ED_NO_COIN
    "Trop de pièces",  // S_ED_TOO_MANY
    "Gomme",  // S_P_ERASE
    "Joueur 1",  // S_P_PLAYER
    "Caisse",  // S_P_BOX
    "Sol",  // S_P_FLOOR
    "Dynamite",  // S_P_DYNAMITE
    "Mur",  // S_P_WALL
    "Pièce",  // S_P_COIN
    "Joueur 2",  // S_P_PLAYER2
    "Caisse joueur 1",  // S_P_BOX1
    "Caisse joueur 2",  // S_P_BOX2
    "Caisse-bombe",  // S_P_BOXBOMB
    "Caisse-mur",  // S_P_BOXWALL
    "Mur fissuré",  // S_P_BREAKABLE
  },
  {  // EN
    "Play",  // S_PLAY
    "How to play",  // S_HOWTO
    "Options",  // S_OPTIONS
    "Credits",  // S_CREDITS
    "Quit",  // S_QUIT
    "Choose a pack",  // S_CHOOSE_PACK
    "%d levels",  // S_LEVELS_FMT
    "Level %d",  // S_LEVEL_FMT
    "by %s",  // S_BY_FMT
    "Coins",  // S_COINS
    "Level complete!",  // S_SOLVED
    "A: next level",  // S_SOLVED_NEXT
    "Pack finished, well done!",  // S_PACK_DONE
    "Too bad, you died!",  // S_DIED
    "A:try again  B:levels",  // S_DIED_HELP
    "Back to the level select?",  // S_CONFIRM_LEVELS
    "Restart the level?",  // S_CONFIRM_RELOAD
    "A:yes  B:no",  // S_CONFIRM_HELP
    "Paused",  // S_PAUSE
    "Resume",  // S_RESUME
    "Restart",  // S_RESTART
    "Level select",  // S_LEVEL_SELECT
    "Title screen",  // S_TO_TITLE
    "Language",  // S_OPT_LANGUAGE
    "Music",  // S_OPT_MUSIC
    "Sound fx",  // S_OPT_SFX
    "All levels open",  // S_OPT_UNLOCK
    "on",  // S_ON
    "off",  // S_OFF
    "Back",  // S_BACK
    "No level pack found",  // S_NO_PACKS
    "Level unreadable",  // S_LOAD_ERROR
    "Screenshot saved",  // S_SHOT_SAVED
    "Screenshot failed",  // S_SHOT_FAILED
    "A:select B:back",  // S_HELP_MENU
    "A:play B:back L/R:+-5",  // S_HELP_LEVELS
    "Collect all the coins.",  // S_HOW1
    "Push boxes (never two at once).",  // S_HOW2
    "Dynamite kills: push a box",  // S_HOW3
    "onto it to blow it up.",  // S_HOW4
    "Bomb box: destroys cracked walls",  // S_HOW5
    "and boxes. Two wall boxes = a wall.",  // S_HOW6
    "A: switch player (2 players)",  // S_HOW7
    "D + d-pad: look around",  // S_HOW8
    "B: levels   C: restart",  // S_HOW9
    "Original game",  // S_CR_TITLE_GAME
    "Graphics",  // S_CR_TITLE_ART
    "Music and sound",  // S_CR_TITLE_SOUND
    "Levels",  // S_CR_TITLE_LEVELS
    "AKA port",  // S_CR_TITLE_PORT
    "%d/%d",  // S_PAGE_FMT
    "Level editor",  // S_EDITOR
    "My packs (editor)",  // S_ED_PACKS_TITLE
    "New pack",  // S_ED_NEW_PACK
    "New level",  // S_ED_NEW_LEVEL
    "Name of the new pack",  // S_ED_NAME_TITLE
    "up/down:letter left/right:place",  // S_ED_NAME_HELP
    "D:delete  A:ok  B:cancel",  // S_ED_NAME_HELP2
    "This name already exists",  // S_ED_EXISTS
    "Test the level",  // S_ED_TEST
    "Save and exit",  // S_ED_SAVE
    "Exit without saving",  // S_ED_DISCARD
    "Clear all",  // S_ED_CLEAR
    "Center the level",  // S_ED_CENTER
    "Level saved",  // S_ED_SAVED
    "Cannot write the file",  // S_ED_SAVE_FAILED
    "Press D again to delete",  // S_ED_DELETE_CONFIRM
    "Test passed!",  // S_ED_TEST_OK
    "A:put C:erase L/R:part D:test B:menu",  // S_ED_HELP
    "A:edit D x2:delete B:back",  // S_ED_LIST_HELP
    "A player is missing",  // S_ED_NO_PLAYER
    "Coins are missing",  // S_ED_NO_COIN
    "Too many parts",  // S_ED_TOO_MANY
    "Eraser",  // S_P_ERASE
    "Player 1",  // S_P_PLAYER
    "Box",  // S_P_BOX
    "Floor",  // S_P_FLOOR
    "Dynamite",  // S_P_DYNAMITE
    "Wall",  // S_P_WALL
    "Coin",  // S_P_COIN
    "Player 2",  // S_P_PLAYER2
    "Box for player 1",  // S_P_BOX1
    "Box for player 2",  // S_P_BOX2
    "Bomb box",  // S_P_BOXBOMB
    "Wall box",  // S_P_BOXWALL
    "Cracked wall",  // S_P_BREAKABLE
  },
  {  // DE
    "Spielen",  // S_PLAY
    "Spielanleitung",  // S_HOWTO
    "Optionen",  // S_OPTIONS
    "Mitwirkende",  // S_CREDITS
    "Beenden",  // S_QUIT
    "Wähle ein Paket",  // S_CHOOSE_PACK
    "%d Level",  // S_LEVELS_FMT
    "Level %d",  // S_LEVEL_FMT
    "von %s",  // S_BY_FMT
    "Münzen",  // S_COINS
    "Level geschafft!",  // S_SOLVED
    "A: nächstes Level",  // S_SOLVED_NEXT
    "Paket gelöst, bravo!",  // S_PACK_DONE
    "Schade, gestorben!",  // S_DIED
    "A:nochmal  B:Level",  // S_DIED_HELP
    "Zurück zur Levelwahl?",  // S_CONFIRM_LEVELS
    "Level neu starten?",  // S_CONFIRM_RELOAD
    "A:ja  B:nein",  // S_CONFIRM_HELP
    "Pause",  // S_PAUSE
    "Weiter",  // S_RESUME
    "Neustart",  // S_RESTART
    "Levelauswahl",  // S_LEVEL_SELECT
    "Titelbild",  // S_TO_TITLE
    "Sprache",  // S_OPT_LANGUAGE
    "Musik",  // S_OPT_MUSIC
    "Effekte",  // S_OPT_SFX
    "Alle Level offen",  // S_OPT_UNLOCK
    "an",  // S_ON
    "aus",  // S_OFF
    "Zurück",  // S_BACK
    "Keine Levelpakete",  // S_NO_PACKS
    "Level unlesbar",  // S_LOAD_ERROR
    "Bildschirmfoto gespeichert",  // S_SHOT_SAVED
    "Bildschirmfoto fehlgeschlagen",  // S_SHOT_FAILED
    "A:wählen B:zurück",  // S_HELP_MENU
    "A:los B:zurück L/R:+-5",  // S_HELP_LEVELS
    "Sammle alle Münzen.",  // S_HOW1
    "Schiebe Kisten (nie zwei).",  // S_HOW2
    "Dynamit tötet: schiebe eine",  // S_HOW3
    "Kiste darauf, um ihn zu sprengen.",  // S_HOW4
    "Bombenkiste: zerstört rissige",  // S_HOW5
    "Wände. Zwei Wandkisten = Wand.",  // S_HOW6
    "A: Spieler wechseln (2 Spieler)",  // S_HOW7
    "D + Kreuz: umsehen",  // S_HOW8
    "B: Level   C: Neustart",  // S_HOW9
    "Originalspiel",  // S_CR_TITLE_GAME
    "Grafik",  // S_CR_TITLE_ART
    "Musik und Klang",  // S_CR_TITLE_SOUND
    "Level",  // S_CR_TITLE_LEVELS
    "AKA-Portierung",  // S_CR_TITLE_PORT
    "%d/%d",  // S_PAGE_FMT
    "Leveleditor",  // S_EDITOR
    "Meine Pakete (Editor)",  // S_ED_PACKS_TITLE
    "Neues Paket",  // S_ED_NEW_PACK
    "Neues Level",  // S_ED_NEW_LEVEL
    "Name des neuen Pakets",  // S_ED_NAME_TITLE
    "hoch/runter:Buchst. links/rechts",  // S_ED_NAME_HELP
    "D:löschen  A:ok  B:abbrechen",  // S_ED_NAME_HELP2
    "Name existiert schon",  // S_ED_EXISTS
    "Level testen",  // S_ED_TEST
    "Speichern und beenden",  // S_ED_SAVE
    "Ohne Speichern beenden",  // S_ED_DISCARD
    "Alles löschen",  // S_ED_CLEAR
    "Level zentrieren",  // S_ED_CENTER
    "Level gespeichert",  // S_ED_SAVED
    "Schreiben fehlgeschlagen",  // S_ED_SAVE_FAILED
    "D nochmal: löschen",  // S_ED_DELETE_CONFIRM
    "Test bestanden!",  // S_ED_TEST_OK
    "A:setzen C:weg L/R:Teil D:Test B:Menü",  // S_ED_HELP
    "A:ändern D x2:löschen B:zurück",  // S_ED_LIST_HELP
    "Spieler fehlt",  // S_ED_NO_PLAYER
    "Münzen fehlen",  // S_ED_NO_COIN
    "Zu viele Teile",  // S_ED_TOO_MANY
    "Radierer",  // S_P_ERASE
    "Spieler 1",  // S_P_PLAYER
    "Kiste",  // S_P_BOX
    "Boden",  // S_P_FLOOR
    "Dynamit",  // S_P_DYNAMITE
    "Wand",  // S_P_WALL
    "Münze",  // S_P_COIN
    "Spieler 2",  // S_P_PLAYER2
    "Kiste Spieler 1",  // S_P_BOX1
    "Kiste Spieler 2",  // S_P_BOX2
    "Bombenkiste",  // S_P_BOXBOMB
    "Wandkiste",  // S_P_BOXWALL
    "Rissige Wand",  // S_P_BREAKABLE
  },
  {  // ES
    "Jugar",  // S_PLAY
    "Cómo jugar",  // S_HOWTO
    "Opciones",  // S_OPTIONS
    "Créditos",  // S_CREDITS
    "Salir",  // S_QUIT
    "Elige un pack",  // S_CHOOSE_PACK
    "%d niveles",  // S_LEVELS_FMT
    "Nivel %d",  // S_LEVEL_FMT
    "por %s",  // S_BY_FMT
    "Monedas",  // S_COINS
    "¡Nivel completado!",  // S_SOLVED
    "A: nivel siguiente",  // S_SOLVED_NEXT
    "¡Pack terminado, bravo!",  // S_PACK_DONE
    "¡Qué pena, has muerto!",  // S_DIED
    "A:reintentar  B:niveles",  // S_DIED_HELP
    "¿Volver a elegir nivel?",  // S_CONFIRM_LEVELS
    "¿Reiniciar el nivel?",  // S_CONFIRM_RELOAD
    "A:sí  B:no",  // S_CONFIRM_HELP
    "Pausa",  // S_PAUSE
    "Continuar",  // S_RESUME
    "Reiniciar",  // S_RESTART
    "Elegir nivel",  // S_LEVEL_SELECT
    "Pantalla de título",  // S_TO_TITLE
    "Idioma",  // S_OPT_LANGUAGE
    "Música",  // S_OPT_MUSIC
    "Efectos",  // S_OPT_SFX
    "Todos los niveles",  // S_OPT_UNLOCK
    "sí",  // S_ON
    "no",  // S_OFF
    "Volver",  // S_BACK
    "Ningún pack de niveles",  // S_NO_PACKS
    "Nivel ilegible",  // S_LOAD_ERROR
    "Captura guardada",  // S_SHOT_SAVED
    "Captura imposible",  // S_SHOT_FAILED
    "A:aceptar B:volver",  // S_HELP_MENU
    "A:jugar B:volver L/R:+-5",  // S_HELP_LEVELS
    "Recoge todas las monedas.",  // S_HOW1
    "Empuja cajas (nunca dos).",  // S_HOW2
    "La dinamita mata: empuja una",  // S_HOW3
    "caja encima para hacerla estallar.",  // S_HOW4
    "Caja bomba: destruye muros",  // S_HOW5
    "agrietados. Dos cajas muro = muro.",  // S_HOW6
    "A: cambiar de jugador (2)",  // S_HOW7
    "D + cruz: mirar alrededor",  // S_HOW8
    "B: niveles   C: reiniciar",  // S_HOW9
    "Juego original",  // S_CR_TITLE_GAME
    "Gráficos",  // S_CR_TITLE_ART
    "Música y sonido",  // S_CR_TITLE_SOUND
    "Niveles",  // S_CR_TITLE_LEVELS
    "Versión AKA",  // S_CR_TITLE_PORT
    "%d/%d",  // S_PAGE_FMT
    "Editor de niveles",  // S_EDITOR
    "Mis packs (editor)",  // S_ED_PACKS_TITLE
    "Nuevo pack",  // S_ED_NEW_PACK
    "Nuevo nivel",  // S_ED_NEW_LEVEL
    "Nombre del nuevo pack",  // S_ED_NAME_TITLE
    "arr/abj:letra izq/der:lugar",  // S_ED_NAME_HELP
    "D:borrar  A:ok  B:cancelar",  // S_ED_NAME_HELP2
    "Ese nombre ya existe",  // S_ED_EXISTS
    "Probar el nivel",  // S_ED_TEST
    "Guardar y salir",  // S_ED_SAVE
    "Salir sin guardar",  // S_ED_DISCARD
    "Borrar todo",  // S_ED_CLEAR
    "Centrar el nivel",  // S_ED_CENTER
    "Nivel guardado",  // S_ED_SAVED
    "No se pudo escribir",  // S_ED_SAVE_FAILED
    "D otra vez: borrar",  // S_ED_DELETE_CONFIRM
    "¡Prueba superada!",  // S_ED_TEST_OK
    "A:poner C:borra L/R:pieza D:test B:menú",  // S_ED_HELP
    "A:editar D x2:borrar B:volver",  // S_ED_LIST_HELP
    "Falta un jugador",  // S_ED_NO_PLAYER
    "Faltan monedas",  // S_ED_NO_COIN
    "Demasiadas piezas",  // S_ED_TOO_MANY
    "Goma",  // S_P_ERASE
    "Jugador 1",  // S_P_PLAYER
    "Caja",  // S_P_BOX
    "Suelo",  // S_P_FLOOR
    "Dinamita",  // S_P_DYNAMITE
    "Muro",  // S_P_WALL
    "Moneda",  // S_P_COIN
    "Jugador 2",  // S_P_PLAYER2
    "Caja jugador 1",  // S_P_BOX1
    "Caja jugador 2",  // S_P_BOX2
    "Caja bomba",  // S_P_BOXBOMB
    "Caja muro",  // S_P_BOXWALL
    "Muro agrietado",  // S_P_BREAKABLE
  },
  {  // IT
    "Gioca",  // S_PLAY
    "Come si gioca",  // S_HOWTO
    "Opzioni",  // S_OPTIONS
    "Crediti",  // S_CREDITS
    "Esci",  // S_QUIT
    "Scegli un pacchetto",  // S_CHOOSE_PACK
    "%d livelli",  // S_LEVELS_FMT
    "Livello %d",  // S_LEVEL_FMT
    "di %s",  // S_BY_FMT
    "Monete",  // S_COINS
    "Livello completato!",  // S_SOLVED
    "A: livello successivo",  // S_SOLVED_NEXT
    "Pacchetto finito, bravo!",  // S_PACK_DONE
    "Peccato, sei morto!",  // S_DIED
    "A:riprova  B:livelli",  // S_DIED_HELP
    "Tornare alla scelta livello?",  // S_CONFIRM_LEVELS
    "Ricominciare il livello?",  // S_CONFIRM_RELOAD
    "A:sì  B:no",  // S_CONFIRM_HELP
    "Pausa",  // S_PAUSE
    "Riprendi",  // S_RESUME
    "Ricomincia",  // S_RESTART
    "Scelta livello",  // S_LEVEL_SELECT
    "Schermata titolo",  // S_TO_TITLE
    "Lingua",  // S_OPT_LANGUAGE
    "Musica",  // S_OPT_MUSIC
    "Effetti",  // S_OPT_SFX
    "Tutti i livelli",  // S_OPT_UNLOCK
    "sì",  // S_ON
    "no",  // S_OFF
    "Indietro",  // S_BACK
    "Nessun pacchetto",  // S_NO_PACKS
    "Livello illeggibile",  // S_LOAD_ERROR
    "Schermata salvata",  // S_SHOT_SAVED
    "Schermata non riuscita",  // S_SHOT_FAILED
    "A:ok B:indietro",  // S_HELP_MENU
    "A:gioca B:indietro L/R:+-5",  // S_HELP_LEVELS
    "Raccogli tutte le monete.",  // S_HOW1
    "Spingi le casse (mai due).",  // S_HOW2
    "La dinamite uccide: spingi una",  // S_HOW3
    "cassa sopra per farla esplodere.",  // S_HOW4
    "Cassa bomba: distrugge muri",  // S_HOW5
    "crepati. Due casse muro = muro.",  // S_HOW6
    "A: cambia giocatore (2)",  // S_HOW7
    "D + croce: guarda attorno",  // S_HOW8
    "B: livelli   C: ricomincia",  // S_HOW9
    "Gioco originale",  // S_CR_TITLE_GAME
    "Grafica",  // S_CR_TITLE_ART
    "Musica e suoni",  // S_CR_TITLE_SOUND
    "Livelli",  // S_CR_TITLE_LEVELS
    "Porting AKA",  // S_CR_TITLE_PORT
    "%d/%d",  // S_PAGE_FMT
    "Editor di livelli",  // S_EDITOR
    "I miei pacchetti (editor)",  // S_ED_PACKS_TITLE
    "Nuovo pacchetto",  // S_ED_NEW_PACK
    "Nuovo livello",  // S_ED_NEW_LEVEL
    "Nome del nuovo pacchetto",  // S_ED_NAME_TITLE
    "su/giu:lettera sx/dx:posto",  // S_ED_NAME_HELP
    "D:cancella  A:ok  B:annulla",  // S_ED_NAME_HELP2
    "Questo nome esiste già",  // S_ED_EXISTS
    "Prova il livello",  // S_ED_TEST
    "Salva ed esci",  // S_ED_SAVE
    "Esci senza salvare",  // S_ED_DISCARD
    "Cancella tutto",  // S_ED_CLEAR
    "Centra il livello",  // S_ED_CENTER
    "Livello salvato",  // S_ED_SAVED
    "Scrittura impossibile",  // S_ED_SAVE_FAILED
    "D ancora: elimina",  // S_ED_DELETE_CONFIRM
    "Test superato!",  // S_ED_TEST_OK
    "A:metti C:canc L/R:pezzo D:test B:menu",  // S_ED_HELP
    "A:modifica D x2:elimina B:indietro",  // S_ED_LIST_HELP
    "Manca un giocatore",  // S_ED_NO_PLAYER
    "Mancano le monete",  // S_ED_NO_COIN
    "Troppi pezzi",  // S_ED_TOO_MANY
    "Gomma",  // S_P_ERASE
    "Giocatore 1",  // S_P_PLAYER
    "Cassa",  // S_P_BOX
    "Pavimento",  // S_P_FLOOR
    "Dinamite",  // S_P_DYNAMITE
    "Muro",  // S_P_WALL
    "Moneta",  // S_P_COIN
    "Giocatore 2",  // S_P_PLAYER2
    "Cassa giocatore 1",  // S_P_BOX1
    "Cassa giocatore 2",  // S_P_BOX2
    "Cassa bomba",  // S_P_BOXBOMB
    "Cassa muro",  // S_P_BOXWALL
    "Muro crepato",  // S_P_BREAKABLE
  },
};

static const char* const NAMES[LANG_COUNT] = { "Français", "English", "Deutsch", "Español", "Italiano" };

void set_lang(int l) { s_lang = (l >= 0 && l < LANG_COUNT) ? l : FR; }
int lang() { return s_lang; }
const char* lang_name(int l) { return (l >= 0 && l < LANG_COUNT) ? NAMES[l] : NAMES[EN]; }
const char* tr(Str s) { return (s >= 0 && s < S_COUNT) ? T[s_lang][s] : ""; }

}  // namespace i18n
